blank_issues_enabled: false
contact_links:
  - name: Security concerns
    url: https://github.com/Antiz96/zaman/blob/main/SECURITY.md
    about: For security concerns, please send a mail to robincandau@protonmail.com instead of opening a public issue
  - name: Contributing guidelines
    url: https://github.com/Antiz96/zaman/blob/main/CONTRIBUTING.md
    about: Please, read the contributing guidelines before opening an issue
